### ISSUE TITLE
Possible bug with kafka and nippy in maven 1.17.1

### ISSUE THREAD

**Issue by nivekuil** [xtdb/xtdb#1562]
![image](https://user-images.githubusercontent.com/4633048/124352390-d0496800-dbb4-11eb-87d1-eab60d2ea3a3.png)

Got this stacktrace on the maven 1.17.1 whenever submitting a tx to kafka, changed back to clojars and it was gone. Oddly I didn't run into this on my dev setup which also uses kafka, but the stacktrace seems to indict something in Crux. Apologies for screenshot, copying the colored log lines does not go well.

**Comment by lispyclouds** [comment]
Happens for me with Postgres+JDBC too
https://github.com/bob-cd/bob/runs/2979066273?check_suite_focus=true#step:7:504

**Comment by jarohen** [comment]
Thanks @nivekuil & @lispyclouds, we'll take a look :)

**Comment by jarohen** [comment]
@lispyclouds: raised bob-cd/bob#106, looks like there was a duplicate `crux-jdbc` dependency being pulled in.
@nivekuil: could you rule this one out too?

Cheers! :)

**Comment by jarohen** [comment]
@nivekuil on second thoughts yours looks less likely to be caused by this given the `juxt.clojars-mirrors` namespace prefix in the stack trace (the Bob one had `crux.jdbc` directly calling through to `taoensso.nippy`). Will keep digging

**Comment by lispyclouds** [comment]
Awesome! Thanks a lot for this @jarohen ! I'll merge and try out all the parts! 😄

**Comment by jarohen** [comment]
@nivekuil - tried to repro but the following goes through ok:

docker-compose.yml:
```
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.1.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
```

`docker-compose up`

deps.edn:
```clojure
{:deps {pro.juxt.crux/crux-core {:mvn/version "1.17.1"}
        pro.juxt.crux/crux-kafka {:mvn/version "1.17.1"}

        com.fasterxml.jackson.core/jackson-core {:mvn/version "2.10.2"}
        com.fasterxml.jackson.core/jackson-databind {:mvn/version "2.10.2"}}}
```

REPL:
```
(require '[crux.api :as crux])

(def node
  (crux/start-node {:crux/tx-log {:crux/module 'crux.kafka/->tx-log}}))

(crux/submit-tx node [[:crux.tx/put {:crux.db/id :foo}]])

(crux/await-tx node *1)
```

Guessing there's something more complex about the transactions that you're putting through - anything specific we could try?
