### ISSUE TITLE
Add configurable retryOptions to Azure ObjectStore component 

### ISSUE THREAD

**Issue by danmason** [xtdb/xtdb#3880]
When setting up the Azure SDK client for working with AzureBlobs, we currently do not set any `RetryOptions` setting overrides. In the case of certain failures being returned from the Client, the SDK would use the **default** retry settings, documented under [**here**](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-retry-policy-java).

We'd like to provide _some_ ability for advanced users to override these settings (though we should generally stick with the defaults otherwise). Current thinking is along the lines of the following under the azure YAML config:
```
storage: !Remote
  objectStore: !Azure
    storageAccount: "foo"
    container: "bar"
    prefix: "object-store"
    retryOptions:
      retryPolicyType: EXPONENTIAL
      maxTries: 5
      retryDelayInMs: 100
      maxRetryDelayInMs: 400
```
